### PR TITLE
Remove twitter

### PR DESCRIPTION
**Pull request by derekjohnson**
## Issue

Twitter have removed their share count endpoint.
## Solution
- Removed the code that did the call to Twitter.
- Removed the `twitter` property from the `networks` object.
- Updated the design so one missing counter doesn't throw the whole thing.

screen shot 2015-11-25 at 19 13 51

Fixes #5

### CODE REVIEW

**Comment by derekjohnson** [comment]
@tosbourn Can you take a look at this before deciding definitely not to use share counts. Another factor to consider is that this new method is giving us roughly 7 times the amount of shares addthis was reporting.

**Comment by tosbourn** [comment]
I think that is fine.

If @gaverinobambino is good with the visuals then :+1:

**Comment by xoxoxo** [comment]
maybe we should have just total share counter?

**Comment by tosbourn** [comment]
@xoxoxo do you mean something like:

Shares: 492 [t] [f] [ln] [etc]

**Comment by derekjohnson** [comment]
@tosbourn @xoxoxo Like it already is? 
screen shot 2015-11-26 at 12 40 38

**Comment by xoxoxo** [comment]
yep

**Comment by tosbourn** [comment]
I liked my diagram better. But yeah, works for me!

**Comment by derekjohnson** [comment]
So don't use share counts on buttons? Is that decided?

**Comment by tosbourn** [comment]
Yes

**Comment by derekjohnson** [comment]
As this is now an open source project can we keep the counters in but remove them from our closed source projects?

This will need merged anyway as it affects the total functionality too.

**Comment by tosbourn** [comment]
That makes sense.

**Pull request merged**
